# Default values for em.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

config:
  s3:
    endpoint: ""
    bucket: xxx
    key: xxx
    secret: xxx
  mattermost:
    token: xxx
    team: xxx
    url: http://mattermost-team-edition.chat.svc
    port: 8065
    external: https://kix.co.il
  cloudflare:
    token: xxx
    account: xxx
    email: xxx
  web:
    url: email.kix.co.il
    secret: xxx
    debug: false

oauth2proxy:
  enable: true
  domain: email.kix.co.il
  config:
    clientID: xxx
    clientSecret: xxx
    cookieSecret: xxx
  extraArgs:
    cookie-domain: email.kix.co.il
    set-xauthrequest: false
    set-authorization-header: false
    login-url: https://kix.co.il/oauth/authorize
    profile-url: https://kix.co.il/api/v4/users/me
    provider: facebook
    provider-display-name: kix.co.il chat
    redeem-url: https://kix.co.il/oauth/access_token
    redirect-url: https://email.kix.co.il/oauth2/callback
    # false is "true" for boolean variables
  ingress:
    enabled: true
    path: /oauth2
    hosts:
      - email.kix.co.il

image:
  repository: phntom/email-manager
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: email.kix.co.il
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  containerPort: 8579

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
