apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "email-manager.fullname" . }}
data:
  BOT_TOKEN: {{ .Values.config.mattermost.token | b64enc | quote }}
  MATTERMOST_TEAM_ID: {{ .Values.config.mattermost.team | b64enc | quote }}
  MATTERMOST_URL: {{ .Values.config.mattermost.url | b64enc | quote }}
  MATTERMOST_PORT: {{ .Values.config.mattermost.port | toString | b64enc | quote }}
  MATTERMOST_EXTERNAL: {{ .Values.config.mattermost.external | b64enc | quote }}
  OP_URL_PREFIX: {{ printf "http://%s.%s.svc" (include "email-manager.fullname" .) .Release.Namespace | b64enc | quote }}
  OP_SECRET: {{ .Values.config.web.secret | b64enc | quote }}
  CLOUDFLARE_TOKEN: {{ .Values.config.cloudflare.token | b64enc | quote }}
  CLOUDFLARE_ACCOUNT: {{ .Values.config.cloudflare.account | b64enc | quote }}
  CLOUDFLARE_EMAIL: {{ .Values.config.cloudflare.email | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.config.s3.key | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.config.s3.secret | b64enc | quote }}
  S3_BUCKET_NAME: {{ .Values.config.s3.bucket | b64enc | quote }}
  S3_ENDPOINT_URL: {{ .Values.config.s3.endpoint | b64enc | quote }}

